lidar_driver:
  ros__parameters:
    use_sim_time: True

    sim:
      model: "cloi"
      parts: "lidar"
      ip_address: "127.0.0.1"
      manager_port: 25554

    remapping_list: ['/tf', '/tf_static']

    transform: [0.27000, 0.0, 0.1125, 0.0, 0.0, 0.0]
    intensity: False

    frame_id: "base_scan"
    topic_name: "scan"

    filter:
      lower_angle: -1.85005
      upper_angle: 1.85005

micom_driver:
  ros__parameters:
    use_sim_time: True

    sim:
      model: "cloi"
      parts_tx: "MICOM_INPUT"
      parts_rx: "MICOM_SENSOR"
      ip_address: "127.0.0.1"
      manager_port: 25554

    remapping_list: ['/tf', '/tf_static']

    wheel:
      base: 449.0
      radius: 95.5

camera_driver:
  ros__parameters:
    use_sim_time: True
    sim:
      model: "cloi"
      parts: "camera"
      ip_address: "127.0.0.1"
      manage_port: 25554

    remapping_list: ['/tf', '/tf_static']

    frame_id: "camera_link"
    camera_name: "camera"

    transform: [0.344000, 0.0, 1.014100, 0.0, 0.0, 0.0]

multi_camera_driver:
  ros__parameters:
    use_sim_time: True
    sim:
      model: "cloi"
      parts: "multi_camera"
      ip_address: "127.0.0.1"
      manage_port: 25554

    remapping_list: ['/tf', '/tf_static']

    camera_name: "multi_camera"
    transform: [-0.048500, 0.0, 0.948300, 0.0, -1.5707, 0.0]
    camera_list: ["left", "right"]

    left:
      name: "left"
      transform_offset: [0.0, 0.252, 0.0, -0.0, -0.0, 0.785398]
      frame_id: "left_link"

    right:
      name: "right"
      transform_offset: [0.0, -0.252, 0.0, -0.0, -0.0, -0.785398]
      frame_id: "right_link"
