micom_driver:
  ros__parameters:
    use_sim_time: True

    sim:
      model: "cloi"
      parts_tx: "MICOM_INPUT"
      parts_rx: "MICOM_SENSOR"
      manager_ip: "127.0.0.1"
      manager_port: 25554

    remapping_list: ['/tf', '/tf_static']

    transform_name:
      imu: "imu"
      wheels: ["wheel_left", "wheel_right"]