depth_camera_driver:
  ros__parameters:
    use_sim_time: True

    sim:
      model: "cloi"
      parts: "depthcamera"

    remapping_list: ['/tf', '/tf_static']

    topic_name: "depth"
    frame_id: "depth_link"