

lidar_driver_sim:
  ros__parameters:
    use_sim_time: True

    sim:
      model: "cloi"
      parts: "lidar"
      ip_address: "127.0.0.1"
      manager_port: 25554

    remapping_list: ['/tf', '/tf_static']

    transform: [0.27000, 0.0, 0.1125, 0.0, 0.0, 0.0]
    intensity: False

    frame_id: "base_scan"
    topic_name: "scan"

    filter:
      lower_angle: -1.85005
      upper_angle: 1.85005

micom_driver_sim:
  ros__parameters:
    use_sim_time: True

    sim:
      model: "cloi"
      parts_tx: "MICOM_INPUT"
      parts_rx: "MICOM_SENSOR"
      ip_address: "127.0.0.1"
      manager_port: 25554

    remapping_list: ['/tf', '/tf_static']

    wheel:
      base: 449.0
      radius: 95.5