depth_camera_driver:
  ros__parameters:
    use_sim_time: True
    
    sim:
      model: "cloi"
      parts: "depthcamera"
      manager_ip: "127.0.0.1"
      manager_port: 25554

    remapping_list: ['/tf', '/tf_static']

    topic_name: "depth"
    frame_id: "depth_link"