multi_camera_driver:
  ros__parameters:
    use_sim_time: True

    sim:
      model: "cloi"
      parts: "multi_camera"

    remapping_list: ['/tf', '/tf_static']

    camera_name: "multi_camera"
    frame_id: ["left", "right"]
