depth_camera_driver:
  ros__parameters:
    use_sim_time: True
    sim:
      model: "cloi"
      parts: "depthcamera"
      manager_ip: "127.0.0.1"
      manager_port: 25554

    remapping_list: ['/tf', '/tf_static']

    frame_id: "link"
    camera_name: "depthcamera"
    camera_info:
      width: 640
      height: 480
      hfov: 1.59174
      distortion:
        k1: 0.10369
        k2: 0.10328
        k3: 0.0
        t1: 0.0
        t2: 0.0

    transform: [0.344000, 0.0, 1.014100, 0.0, 0.0, 0.0]