realsense_driver:
  ros__parameters:
    use_sim_time: True

    sim:
      model: "cloi"
      parts: "realsense"

    remapping_list: ['/tf', '/tf_static']

    topic_name: "realsense"
    frame_id: "realsense_link"
    module_list: ["rgb", "ir1", "ir2", "depth"]
