camera_driver:
  ros__parameters:
    use_sim_time: True

    sim:
      model: "cloi"
      parts: "camera"

    remapping_list: ['/tf', '/tf_static']

    topic_name: "rgb"
    frame_id: "camera_link"