lidar_driver:
  ros__parameters:
    use_sim_time: True

    sim:
      model: "cloi"
      parts: "lidar"
      manager_ip: "127.0.0.1"
      manager_port: 25554

    remapping_list: ['/tf', '/tf_static']

    transform: [0.27000, 0.0, 0.1125, 0.0, 0.0, 0.0]
    intensity: False

    frame_id: "base_scan"
    topic_name: "scan"

    filter:
      lower_angle: -1.85005
      upper_angle: 1.85005